### ISSUE TITLE
Usernames and folder names that match the ignore list break loading

### ISSUE THREAD

**Issue by gigaherz** [MinecraftForge/bootstraplauncher#6]
The folder name `C:\Users\rasmussen\AppData\Roaming\.minecraft` contains the string "asm" in it, and so all libraries in the minecraft library repository are ignored. As a result, forge can't load.

![username](https://cdn.discordapp.com/attachments/437001959950778368/874318970436608031/unknown.png)

The error:
![error](https://cdn.discordapp.com/attachments/437001959950778368/874323620632084500/unknown.png)

A workaround is creating a new account without "asm" in the name, but this is highly inconvenient for most people.

**Comment by Rongmario** [comment]
Any explanation of why the string "asm" would induce this? Seems unreasonable.

**Comment by DaemonUmbra** [comment]
Lazy programming... using "asm" as a filter string and using .contains as the check

**Comment by gigaherz** [comment]
It's due to the ignoreList written in the version json: 

```
        "jvm": [
            "-DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,client-extra,fmlcore,javafmllanguage,mclanguage,forge-,${version_name}.jar",
```

The same would happen if your windows username was something like "forge-of-gods" since it would match the "forge-" ignore entry instead.

**Comment by LexManos** [comment]
We've tried explicit version numbers, however modlauncher uses a wildcard and thus breaks that.
We need to make this a lot more robust, but still flexible. 
Honestly we could try path.getFileName().startsWith() to be a bit more strict.
